# Generated by Django 3.1.7 on 2021-05-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='http://localhost:8000', max_length=255),
            preserve_default=False,
        ),
    ]
