# Generated by Django 3.1.7 on 2022-02-04 18:05

from django.db import migrations, models
import django.db.models.deletion
import product_shop.validators.image_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', validators=[product_shop.validators.image_validators.poster_size_validator])),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.poster')),
            ],
        ),
    ]
