# Generated by Django 3.1.7 on 2021-06-05 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_image_image_url'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('payment_method', models.IntegerField(choices=[(1, 'CASH'), (2, 'ONLINE')])),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'COMPLETE'), (2, 'CANCELED'), (3, 'IN PROGRESS')])),
                ('transaction_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
